### ISSUE TITLE
bin/tapioca dsl undefined method `config' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ccoffey** [Shopify/tapioca#1080]
Version of Tapioca that I am using:
```
bin/tapioca --version                                                  
Tapioca v0.9.2
```

Version of Ruby that I am using:
```
cat .ruby-version 
2.7.5
```

Version of Rails that I am using:
```
grep "'rails'" Gemfile
gem 'rails', '7.0.3.1'
```

The error:

```
bin/tapioca dsl
Loading Rails application... Traceback (most recent call last):
	33: from bin/tapioca:29:in `<main>'
	32: from bin/tapioca:29:in `load'
	31: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/exe/tapioca:23:in `<top (required)>'
	30: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	29: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	28: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	27: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	26: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca/cli.rb:144:in `dsl'
	25: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	24: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
	23: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca.rb:17:in `silence_warnings'
	22: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
	21: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca.rb:18:in `block in silence_warnings'
	20: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca/cli.rb:145:in `block in dsl'
	19: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	18: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
	17: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca/commands/dsl.rb:67:in `execute'
	16: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	15: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
	14: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca/commands/dsl.rb:138:in `load_application'
	13: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	12: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
	11: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca/runtime/loader.rb:37:in `load_rails_application'
	10: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	 9: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
	 8: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/tapioca-0.9.2/lib/tapioca/runtime/loader.rb:87:in `eager_load_rails_app'
	 7: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:62:in `run_load_hooks'
	 6: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:62:in `each'
	 5: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:63:in `block in run_load_hooks'
	 4: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:77:in `execute_hook'
	 3: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:72:in `with_execution_control'
	 2: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:79:in `block in execute_hook'
	 1: from /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/i18n_railtie.rb:26:in `block in <class:Railtie>'
/home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/i18n_railtie.rb:35:in `initialize_i18n': undefined method `config' for nil:NilClass (NoMethodError)
```

**Comment by ccoffey** [comment]
I noticed that `lib/tapioca/runtime/loader.rb` no longer exists in the [main branch](https://github.com/Shopify/tapioca/blob/main/lib/tapioca/runtime/loader.rb) so I decided to try it out!

```diff
-- gem 'tapioca'
++ gem 'tapioca', git: 'https://github.com/Shopify/tapioca', branch: 'main'
```

```
bundle install                 
Fetching https://github.com/Shopify/tapioca
.
.
.
```

Different stack trace, same problem:

```
bundle exec tapioca dsl
Loading Rails application... bundler: failed to load command: tapioca (/home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bin/tapioca)
NoMethodError: undefined method `config' for nil:NilClass
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/i18n_railtie.rb:35:in `initialize_i18n'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/i18n_railtie.rb:26:in `block in <class:Railtie>'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:79:in `block in execute_hook'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:72:in `with_execution_control'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:77:in `execute_hook'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:63:in `block in run_load_hooks'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:62:in `each'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-7.0.3.1/lib/active_support/lazy_load_hooks.rb:62:in `run_load_hooks'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/loaders/loader.rb:109:in `eager_load_rails_app'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/loaders/loader.rb:48:in `load_rails_application'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/loaders/dsl.rb:60:in `load_application'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/loaders/dsl.rb:18:in `load'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/loaders/dsl.rb:12:in `load_application'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/commands/dsl.rb:61:in `execute'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/cli.rb:136:in `block in dsl'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca.rb:18:in `block in silence_warnings'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca.rb:17:in `silence_warnings'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `bind_call'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10219/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/lib/tapioca/cli.rb:135:in `dsl'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/tapioca-7d1b85335cf4/exe/tapioca:23:in `<top (required)>'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bin/tapioca:23:in `load'
  /home/cathal/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bin/tapioca:23:in `<top (required)>'
```

**Comment by ccoffey** [comment]
I only figured this out after removing the rescue here: https://github.com/Shopify/tapioca/blob/b1f4a7b3d2e5c1958a43ee94f87571b3a10d572a/lib/tapioca/runtime/loader.rb#L67-L71

I really think you should remove this and let `tapioca dsl` blow up with a useful error!
