### ISSUE TITLE
Tapioca loads ActiveRecord every time

### ISSUE THREAD

**Issue by miry** [Shopify/tapioca#1425]
Tapioca load activerecord in https://github.com/Shopify/tapioca/blob/d96541002909dc4efcb6ee9273e88e8498b13a45/lib/tapioca/dsl/extensions/active_record.rb
Even the application does not use ActiveRecord.

It made problems, when other gems during initialization checks if ActiveRecord is defined.

```shell
$ bundle exec bin/tapioca dsl
Loading Rails application... 
Tapioca attempted to load the Rails application after encountering a `config/application.rb` file, but it failed.  If your application uses Rails please ensure it can be loaded correctly before generating RBIs.
undefined method `active_record' for #<Rails::Engine::Configuration ...

Continuing RBI generation without loading the Rails application.
Done
bundler: failed to load command: bin/tapioca (bin/tapioca)
/Users/miry/src/github.com/Shopify/tapioca/lib/tapioca/loaders/dsl.rb:79:in `abort_if_pending_migrations!': undefined method `load_tasks' for nil:NilClass (NoMethodError)
```

**Comment by miry** [comment]
I have tested localy to show the first require, and it brought me to this file.
But it could be the problem is presented in 2 places.

**Comment by yathi** [comment]
Is this still something that is worked on? I am running into a similar error in a project that doesn't use `ActiveRecord`. When I try to run `bin/tapioca dsl`, I get: 

```sh
Tapioca attempted to load the Rails application after encountering a `config/application.rb` file, but it failed. If your application uses Rails please ensure it can be loaded correctly before generating RBIs. If your application does not use Rails and you wish to continue RBI generation please pass `--no-halt-upon-load-error` to the tapioca command in sorbet/tapioca/config.yml or in CLI.
ActiveRecord::ConnectionNotEstablished
/home/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.7.2/lib/active_record/connection_handling.rb:309:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
        from /home/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.7.2/lib/active_record/connection_handling.rb:305:in `connection_db_config'
        from /home/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/money-rails-1.15.0/lib/money-rails/hooks.rb:23:in `block in init'
```

**Comment by yathi** [comment]
I did make the change that @dirceu suggested locally, and after that the command does work!
