### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID (NameError)

### ISSUE THREAD

**Issue by Overload119** [Shopify/tapioca#1437]
I've recently started getting this in my application.
I'll debug in this issue until I fix it.
If anyone has an idea where I would look, please let me know.

<details>

```
Error: `Tapioca::Dsl::Compilers::ActiveRecordColumns` failed to generate RBI for `AdCreative`
Traceback (most recent call last):
	48: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
	47: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
	46: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/tapioca:23:in `<main>'
	45: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/bin/tapioca:23:in `load'
	44: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/exe/tapioca:25:in `<top (required)>'
	43: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	42: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	41: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	39: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/cli.rb:155:in `dsl'
	38: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	37: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `bind_call'
	36: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca.rb:22:in `silence_warnings'
	35: from /Users/amirsharif/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
	34: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca.rb:23:in `block in silence_warnings'
	33: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/cli.rb:159:in `block in dsl'
	32: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	31: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `bind_call'
	30: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/commands/dsl.rb:114:in `execute'
	29: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	28: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `bind_call'
	27: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:78:in `run'
	26: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	25: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.10712/lib/types/private/methods/_methods.rb:277:in `bind_call'
	24: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/executor.rb:31:in `run_in_parallel'
	23: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:288:in `map'
	22: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:353:in `work_direct'
	21: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'
	20: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:354:in `block in work_direct'
	19: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
	18: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:79:in `block in run'
	17: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:170:in `rbi_for_constant'
	16: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:170:in `each'
	15: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:174:in `block in rbi_for_constant'
	14: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/active_record_columns.rb:111:in `decorate'
	13: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:16:in `create_path'
	12: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:39:in `create_class'
	11: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:39:in `tap'
	10: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:40:in `block in create_class'
	 9: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/active_record_columns.rb:112:in `block in decorate'
	 8: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:26:in `create_module'
	 7: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:26:in `tap'
	 6: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:27:in `block in create_module'
	 5: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/active_record_columns.rb:113:in `block (2 levels) in decorate'
	 4: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/active_record_columns.rb:113:in `each'
	 3: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/active_record_columns.rb:114:in `block (3 levels) in decorate'
	 2: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/active_record_columns.rb:175:in `add_methods_for_attribute'
	 1: from /Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/helpers/active_record_column_type_helper.rb:22:in `type_for'
/Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/helpers/active_record_column_type_helper.rb:73:in `type_for_activerecord_value': uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID (NameError)
```

<summary>Stack Trace</summary>
</details>

**Comment by Overload119** [comment]
Okay so this error seems to come from a column_type of 

`#<ActiveRecord::Type::Json:0x00007fc1f4db10b0>`

If I drop in 

```rb
require 'active_record/connection_adapters/postgresql/oid.rb' 
```

Inside of 

`/Users/amirsharif/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/dsl/helpers/active_record_column_type_helper.rb`

Then I'm able to compile.

The strange thing is that I'm not using Postgres at all. My DB adapter is MySQL.

I tried adding the require statement in `require.rb` but that didn't work.
Only when I add it inside of `config/application.rb` for my Rails application did I unblock myself.

**Comment by andyw8** [comment]
Hi @Overload119, which version of Rails are you using?

**Comment by palytoxin** [comment]
same issue, rails (7.0.4.3), use only mysql, not pg.  @andyw8
