### ISSUE TITLE
Tapioca init command is throwing an error

### ISSUE THREAD

**Issue by juniorjp** [Shopify/tapioca#1505]
Hi 👋 . Running ` bundle exec tapioca init` throws the following error in my Rails monolith. 

I'm using Tapioca version `0.11.2` and Rails ` 5.0.7.2`

```
Requiring all gems to prepare for compiling... bundler: failed to load command: tapioca (/Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/bin/tapioca)
TypeError: can't create instance of singleton class
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/railties-5.0.7.2/lib/rails/railtie.rb:170:in `new'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/railties-5.0.7.2/lib/rails/railtie.rb:170:in `instance'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/railties-5.0.7.2/lib/rails/railtie.rb:122:in `config'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:163:in `block in engines'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:163:in `reject'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:163:in `engines'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:117:in `load_engines_in_classic_mode'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:73:in `block in load_rails_engines'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:147:in `with_rails_application'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:67:in `load_rails_engines'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/loader.rb:33:in `load_bundle'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/gem.rb:59:in `require_gem_file'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/gem.rb:33:in `load'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/loaders/gem.rb:27:in `load_application'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:243:in `block in perform_additions'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/shell/basic.rb:44:in `indent'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:239:in `perform_additions'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:115:in `sync'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/cli.rb:270:in `block in gem'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca.rb:23:in `block in silence_warnings'
  /Users/reginaldojunior/.rvm/rubies/ruby-2.7.7/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca.rb:22:in `silence_warnings'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/cli.rb:239:in `gem'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/cli.rb:32:in `block in init'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/runtime/trackers.rb:26:in `with_trackers_enabled'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `bind_call'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/sorbet-runtime-0.5.10827/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/lib/tapioca/cli.rb:29:in `init'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/gems/tapioca-0.11.2/exe/tapioca:25:in `<top (required)>'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/bin/tapioca:23:in `load'
  /Users/reginaldojunior/.rvm/gems/ruby-2.7.7@my_app/bin/tapioca:23:in `<top (required)>'
```

I would appreciate any help

**Comment by KaanOzkan** [comment]
Can you run this in a rails console and post the error?
```
Rails::Engine.descendants.reject(&:abstract_railtie?).reject { |engine| engine.config.root.to_path}
```

Error message should contain the exact engine class that threw the exception. Engine may be missing something, I'm thinking that `engine.config` call is going to the wrong class (https://github.com/rails/rails/blob/aea6423f013ca48f7704c70deadf2cd6ac7d70a1/railties/lib/rails/railtie.rb#L122).

**Comment by paracycle** [comment]
Additionally, Rails 5.0.7.2 is way outside our support window and we can't promise any compatibility with it. We follow the Rails guidelines on supported versions and only provide support for the last 2 Rails releases, which are currently 6.1 and 7.0.

If you get to the bottom of the issue and find which Railtie is causing the problem based on @KaanOzkan's suggestion, we could apply a small fix, but we can't guarantee anything will work going forward. Thanks for your understanding.

**Comment by paracycle** [comment]
Closing this for now. Please reopen if you can find the source of the problem.
