### ISSUE TITLE
tapioca init failes: because of gem load error

### ISSUE THREAD

**Issue by yosiat** [Shopify/tapioca#1527]
Hi,

I am trying to run `bundle exec tapioca init` on rails (6.1) project, and it fails since it loads doorkeeper code before the rails initializer happened -
```
/Users/yosi/.rvm/gems/ruby-3.2.0/gems/doorkeeper-5.3.3/lib/doorkeeper/config.rb:24:in `configuration': Configuration for doorkeeper missing. Do you have doorkeeper initializer? (Doorkeeper::MissingConfiguration)
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/doorkeeper-5.3.3/app/controllers/doorkeeper/application_controller.rb:5:in `<module:Doorkeeper>'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/doorkeeper-5.3.3/app/controllers/doorkeeper/application_controller.rb:3:in `<main>'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/tapioca-0.11.6/lib/tapioca/runtime/reflection.rb:50:in `const_get'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/tapioca-0.11.6/lib/tapioca/runtime/reflection.rb:50:in `constantize'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/tapioca-0.11.6/lib/tapioca/runtime/trackers/autoload.rb:25:in `block in eager_load_all!'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/tapioca-0.11.6/lib/tapioca/runtime/trackers/autoload.rb:50:in `with_disabled_exits'
```

Which happens from this code - https://github.com/doorkeeper-gem/doorkeeper/blob/main/app/controllers/doorkeeper/application_controller.rb#L5

Is there anyway to get tapioca load all gems inside a rails environment (like development) ? or at less ask tapioca to ignore doorkeeper for now?

Thanks

**Comment by yosiat** [comment]
I tried another way and stumbled the same issue - generating requires with `bundle exec tapioca require`, then cleaning a bit `require.rb` (wrong requires from my-app code), then ran `bundle exec gem --exclude doorkeeper` and got the same issue:

```
/Users/yosi/.rvm/gems/ruby-3.2.0/gems/doorkeeper-5.3.3/lib/doorkeeper/config.rb:24:in `configuration': Configuration for doorkeeper missing. Do you have doorkeeper initializer? (Doorkeeper::MissingConfiguration)
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/doorkeeper-5.3.3/app/controllers/doorkeeper/application_controller.rb:5:in `<module:Doorkeeper>'
        from /Users/yosi/.rvm/gems/ruby-3.2.0/gems/doorkeeper-5.3.3/app/controllers/doorkeeper/application_controller.rb:3:in `<main>'
```

**Comment by paracycle** [comment]
This was a problem with the Doorkeeper gem and was reported here: https://github.com/doorkeeper-gem/doorkeeper/pull/1615

**Comment by yosiat** [comment]
Thanks @paracycle , I'll upgrade and check that.

There was another issue I was getting (in second comment), but let's see after proper setup with doorkeeper.

**Comment by paracycle** [comment]
The other issue sounds like a Ruby/macOS related problem, you can see others having similar problems with Spring and Vips here: https://github.com/rails/rails/issues/38560

**Comment by iMacTia** [comment]
Hey future reader 👋 

If you're seeing the `[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. ` issue, that is not related to `doorkeeper`. In order to address it, you'll need to set the `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` env variable before running `tapioca`.
