### ISSUE TITLE
tapioca crashes when using good job

### ISSUE THREAD

**Issue by stathis-alexander** [Shopify/tapioca#1557]
Apologies in advance, as I'm not super familiar with the inner workings here and may be misunderstanding. 

We use [GoodJob](https://github.com/bensheldon/good_job), an ActiveJob backend based on postgres. It seems that good job adds some model classes underneath the hood, and it appears when attempting to run the `ActiveRecordAssociation` DSL, tapioca crashes due to being unable to find valid models for the associations. The other active record DSLs run fine. 

Here's the output:
```
Error: `Tapioca::Dsl::Compilers::ActiveRecordAssociations` failed to generate RBI for `GoodJob::ActiveJobJob`
Shutting down background worker
Killing session flusher
/Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4/lib/active_record/reflection.rb:436:in `compute_class': Rails couldn't find a valid model for GoodJob::Batch association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass. (ArgumentError)

            raise ArgumentError, msg
                  ^^^^^^^^^^^^^^^^^^
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4/lib/active_record/reflection.rb:382:in `klass'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:292:in `validate_reflection!'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:269:in `type_for'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:187:in `populate_single_assoc_getter_setter'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:166:in `block in populate_associations'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:162:in `each'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:162:in `populate_associations'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:131:in `block (2 levels) in decorate'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/rbi_ext/model.rb:27:in `block in create_module'
	from <internal:kernel>:90:in `tap'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/rbi_ext/model.rb:26:in `create_module'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:129:in `block in decorate'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/rbi_ext/model.rb:40:in `block in create_class'
	from <internal:kernel>:90:in `tap'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/rbi_ext/model.rb:39:in `create_class'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/rbi_ext/model.rb:16:in `create_path'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/compilers/active_record_associations.rb:128:in `decorate'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/pipeline.rb:174:in `block in rbi_for_constant'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/pipeline.rb:170:in `each'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/pipeline.rb:170:in `rbi_for_constant'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/pipeline.rb:79:in `block in run'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:627:in `call_with_index'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:394:in `block in work_direct'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:637:in `with_instrumentation'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:393:in `work_direct'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:285:in `map'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/executor.rb:31:in `run_in_parallel'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/dsl/pipeline.rb:78:in `run'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/commands/dsl.rb:119:in `execute'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/cli.rb:164:in `block in dsl'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca.rb:23:in `block in silence_warnings'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/user_interaction.rb:46:in `use_ui'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca.rb:22:in `silence_warnings'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10904/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/lib/tapioca/cli.rb:160:in `dsl'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /Users/alex.stathis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.7/exe/tapioca:25:in `<top (required)>'
	from bin/tapioca:31:in `load'
	from bin/tapioca:31:in `<main>'
```

It's strange because it appears to know that the classes in the `GoodJob` module are there because it's attempting to generate rbis for them, but can't seem to find the other ones when generating the association RBIs.

**Comment by stathis-alexander** [comment]
Upgrading GoodJob from v3.12.1 to v3.15.14 (latest) fixes the issue for us, actually.
