### ISSUE TITLE
bin/tapioca dsl failed to generate dsl files

### ISSUE THREAD

**Issue by ArthurJordao** [Shopify/tapioca#1592]
Hello folks!

I am having a issue to generate the dsls on my rails 7 project using tapioca. I tried to run it inside of my project and it is failing with the following error:
```
 bin/tapioca dsl
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
Loading Rails application... Done
Loading DSL compiler classes... Done
Compiling DSL RBI files...

Error: `Tapioca::Dsl::Compilers::MixedInClassAttributes` failed to generate RBI for `AbstractController::Caching::Fragments`
Error: `Tapioca::Dsl::Compilers::MixedInClassAttributes` failed to generate RBI for `AbstractController::Caching`
/Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:40:in `block (2 levels) in declare_abstract': RuntimeError: RBI::Param is declared as abstract; it cannot be instantiated (Parallel::UndumpableException)
        from <internal:kernel>:90:in `tap'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/runtime/dynamic_mixin_compiler.rb:148:in `block (3 levels) in compile_class_attributes'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/rbi-0.0.17/lib/rbi/model.rb:529:in `initialize'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `new'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/runtime/dynamic_mixin_compiler.rb:147:in `block (2 levels) in compile_class_attributes'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/runtime/dynamic_mixin_compiler.rb:146:in `each'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/runtime/dynamic_mixin_compiler.rb:146:in `block in compile_class_attributes'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/rbi-0.0.17/lib/rbi/model.rb:207:in `initialize'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `new'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/runtime/dynamic_mixin_compiler.rb:141:in `compile_class_attributes'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/mixed_in_class_attributes.rb:62:in `block in decorate'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:27:in `block in create_module'
        from <internal:kernel>:90:in `tap'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:26:in `create_module'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/rbi_ext/model.rb:18:in `create_path'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/compilers/mixed_in_class_attributes.rb:61:in `decorate'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:174:in `block in rbi_for_constant'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:170:in `each'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:170:in `rbi_for_constant'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:79:in `block in run'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:627:in `call_with_index'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:597:in `process_incoming_jobs'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:577:in `block in worker'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `fork'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `worker'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:559:in `block in create_workers'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each_with_index'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `create_workers'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:497:in `work_in_processes'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:291:in `map'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/executor.rb:31:in `run_in_parallel'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/dsl/pipeline.rb:78:in `run'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/commands/dsl.rb:114:in `execute'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/cli.rb:159:in `block in dsl'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca.rb:23:in `block in silence_warnings'
        from /nix/store/21ib5qd8lpd767s999ik9h4l504rn6nv-ruby-3.1.4/lib/ruby/3.1.0/rubygems/user_interaction.rb:46:in `use_ui'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca.rb:22:in `silence_warnings'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/sorbet-runtime-0.5.10950/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/lib/tapioca/cli.rb:155:in `dsl'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /Users/arthurjordao/.local/share/gem/ruby/3.1.0/gems/tapioca-0.11.2/exe/tapioca:25:in `<top (required)>'
        from bin/tapioca:29:in `load'
        from bin/tapioca:29:in `<main>'
```

It seems that the error is related with the active records compilers, excluding the following compilers I can generate the the rbi types:

```
gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  exclude:
  - ActiveJob
  - ActiveRecordAssociations
  - ActiveRecordRelations
  - ActiveRecordColumns
  - ActiveStorage
  - ActiveSupportCurrentAttributes
  - MixedInClassAttributes
  # workers: 5
```

**Comment by ArthurJordao** [comment]
Thank you @Morriar. I just updated here and things are working smoothly now.
