### ISSUE TITLE
Internal ArgumentError when running `tapioca gems`

### ISSUE THREAD

**Issue by searls** [Shopify/tapioca#1669]
Seeing this error: `gem/listeners/methods.rb:77:in `method': wrong number of arguments (given 0, expected 1) (ArgumentError)` 

Happens on 0.11.8 and 0.11.9 whenever I attempt to regenerate RBIs in this [branch of mocktail](https://github.com/testdouble/mocktail/tree/tldr).

Any ideas what might cause this? Sorry for the bare bones issue. I don't really know how to debug this.

Output:

```
$ bundle exec tapioca gems
Removing RBI files of gems that have been removed:

      remove  sorbet/rbi/gems/m@1.6.1.rbi
      remove  sorbet/rbi/gems/method_source@1.0.0.rbi
      remove  sorbet/rbi/gems/minitest@5.18.0.rbi

Generating RBI files of gems that are added or updated:

Requiring all gems to prepare for compiling...  Done

  -> Moving: sorbet/rbi/gems/lint_roller@1.0.0.rbi to sorbet/rbi/gems/lint_roller@1.1.0.rbi
  -> Moving: sorbet/rbi/gems/parser@3.2.2.1.rbi to sorbet/rbi/gems/parser@3.2.2.3.rbi
  -> Moving: sorbet/rbi/gems/rbi@0.0.16.rbi to sorbet/rbi/gems/rbi@0.0.17.rbi
  -> Moving: sorbet/rbi/gems/regexp_parser@2.8.0.rbi to sorbet/rbi/gems/regexp_parser@2.8.1.rbi
  -> Moving: sorbet/rbi/gems/rexml@3.2.5.rbi to sorbet/rbi/gems/rexml@3.2.6.rbi
  -> Moving: sorbet/rbi/gems/rubocop@1.52.0.rbi to sorbet/rbi/gems/rubocop@1.56.1.rbi
  Compiled optimist (empty output)
      create  sorbet/rbi/gems/optimist@3.1.0.rbi




/Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:77:in `method': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:77:in `compile_method'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:57:in `block (2 levels) in compile_directly_owned_methods'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:45:in `map'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:45:in `block in compile_directly_owned_methods'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:44:in `each'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:44:in `compile_directly_owned_methods'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/methods.rb:23:in `on_scope'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/listeners/base.rb:26:in `dispatch'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/pipeline.rb:200:in `block in on_node'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/pipeline.rb:200:in `each'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/pipeline.rb:200:in `on_node'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/pipeline.rb:165:in `dispatch'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/gem/pipeline.rb:49:in `compile'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/commands/gem.rb:169:in `compile_gem_rbi'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/commands/gem.rb:264:in `block (2 levels) in perform_additions'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:627:in `call_with_index'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:597:in `process_incoming_jobs'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:577:in `block in worker'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `fork'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:568:in `worker'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:559:in `block in create_workers'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `each_with_index'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:558:in `create_workers'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:497:in `work_in_processes'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:291:in `map'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/executor.rb:31:in `run_in_parallel'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/commands/gem.rb:255:in `block in perform_additions'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/shell/basic.rb:44:in `indent'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/commands/gem.rb:243:in `perform_additions'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/commands/gem.rb:119:in `sync'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/cli.rb:280:in `block in gem'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca.rb:23:in `block in silence_warnings'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/user_interaction.rb:46:in `use_ui'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca.rb:22:in `silence_warnings'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/lib/tapioca/cli.rb:248:in `gem'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.11.8/exe/tapioca:25:in `<top (required)>'
        from bin/tapioca:29:in `load'
        from bin/tapioca:29:in `<main>'
```

**Comment by KaanOzkan** [comment]
This is the first method hitting my breakpoint while generating RBIs for your branch and it's raising https://github.com/testdouble/mocktail/blob/1f50a0143ad8ce10ed7428fadad1d7a219583c35/lib/mocktail.rb#L123-L125.

Rest of the diff in your branch doesn't look important you can reproduce with having mocktail and tldr in the same project. I added them to tapioca and added a breakpoint inside`compile_method`. [This code](https://github.com/tenderlove/tldr/blob/7def1c598aa4c038def8d30ff1e7bdce939da118/lib/tldr/sorbet_compatibility.rb#L6) looked suspicious from `tldr` but it doesn't actually affect it. I can also generate RBIs for tldr without mocktail fine.

Maybe @paracycle can theorize why this is happening. `method` looks good prior to the call.

**Comment by paracycle** [comment]
Ok, finally had some time on my hands to take a look at this and I narrowed it down to `sorbet-eraser` returning the wrong value as the "signature": https://github.com/kddnewton/sorbet-eraser/pull/23
