### ISSUE TITLE
`tapioca dsl` crashes with weird error when Gemfile contains OpenTelemetry gems.

### ISSUE THREAD

**Issue by TwoAbove** [Shopify/tapioca#1743]
Hey! I'm instrumenting a ruby rails app with OpenTelemetry, and I noticed that just adding the 
```
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
```
to the Gemfile causes `tapioca dsl` to crash with this weird error:
```bash
> bundle exec tapioca dsl
...
Error: `Tapioca::Dsl::Compilers::Protobuf` failed to generate RBI for `Google::Protobuf::AbstractMessage`
bundler: failed to load command: tapioca (/Users/seva/.asdf/installs/ruby/3.2.2/bin/tapioca)
/Users/seva/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.10.5/lib/tapioca/dsl/compilers/protobuf.rb:148:in `block in decorate': TypeError: Unexpected descriptor class: NilClass (Parallel::UndumpableException)
        from /Users/seva/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/tapioca-0.10.5/lib/tapioca/rbi_ext/model.rb:40:in `block in create_class'
        from <internal:kernel>:90:in `tap'
...
```
(full stack trace [here](https://gist.github.com/TwoAbove/29c0b422600d76f238b78940a1846d5e))

The weird thing is that we don't use `google-protobuf`, and adding it to the Gemfile doesn't help either. 

Removing the OpenTelemetry gems from the Gemfile allows `tapioca dsl` to succeed. 

I'm at a loss here as to what to do. I tried to find ways to ignore the OpenTelemetry gems, but couldn't find anything that works.

Any suggestions to what I can do here? 

Thanks!

**Comment by TwoAbove** [comment]
I did find this https://github.com/Shopify/tapioca/pull/1411 similar issue

**Comment by TwoAbove** [comment]
Update: I noticed that the tapoica version in that issue was higher than ours, so I'll report back after I update tapioca 😅

**Comment by TwoAbove** [comment]
Looks like just updating helped!
