### ISSUE TITLE
Error: `Tapioca::Compilers::ActiveRecordExtensions` failed to generate RBI for `ActionMailbox::InboundEmail`

### ISSUE THREAD

**Issue by nyghtly-derek** [Shopify/tapioca#1951]
Do you have any idea why this is failing? Is there any other information that you need?

```
> tapioca dsl

Loading DSL extension classes... Done
Loading Rails application... Done
Loading DSL compiler classes... Done
Compiling DSL RBI files...

   identical  sorbet/rbi/dsl/abstract_controller/caching/fragments.rbi
   identical  sorbet/rbi/dsl/abstract_controller/callbacks.rbi
   identical  sorbet/rbi/dsl/abstract_controller/helpers.rbi
   identical  sorbet/rbi/dsl/abstract_controller/rendering.rbi
   identical  sorbet/rbi/dsl/abstract_controller/url_for.rbi
   identical  sorbet/rbi/dsl/action_cable/channel/callbacks.rbi
   identical  sorbet/rbi/dsl/action_cable/channel/periodic_timers.rbi
   identical  sorbet/rbi/dsl/action_cable/connection/identification.rbi
   identical  sorbet/rbi/dsl/action_controller/api_rendering.rbi
   identical  sorbet/rbi/dsl/action_controller/caching.rbi
   identical  sorbet/rbi/dsl/action_controller/conditional_get.rbi
   identical  sorbet/rbi/dsl/action_controller/content_security_policy.rbi
   identical  sorbet/rbi/dsl/action_controller/data_streaming.rbi
   identical  sorbet/rbi/dsl/action_controller/etag_with_flash.rbi
   identical  sorbet/rbi/dsl/action_controller/etag_with_template_digest.rbi
   identical  sorbet/rbi/dsl/action_controller/flash.rbi
   identical  sorbet/rbi/dsl/action_controller/form_builder.rbi
   identical  sorbet/rbi/dsl/action_controller/helpers.rbi
   identical  sorbet/rbi/dsl/action_controller/params_wrapper.rbi
   identical  sorbet/rbi/dsl/action_controller/redirecting.rbi
   identical  sorbet/rbi/dsl/action_controller/renderers.rbi
   identical  sorbet/rbi/dsl/action_controller/renderers/all.rbi
   identical  sorbet/rbi/dsl/action_controller/request_forgery_protection.rbi
   identical  sorbet/rbi/dsl/action_controller/rescue.rbi
   identical  sorbet/rbi/dsl/action_controller/respond_with.rbi
   identical  sorbet/rbi/dsl/action_controller/test_case/behavior.rbi
   identical  sorbet/rbi/dsl/action_controller/url_for.rbi
   identical  sorbet/rbi/dsl/action_dispatch/integration_test.rbi
   identical  sorbet/rbi/dsl/action_dispatch/routing/route_set/mounted_helpers.rbi
   identical  sorbet/rbi/dsl/action_dispatch/routing/url_for.rbi
Error: `Tapioca::Compilers::ActiveRecordExtensions` failed to generate RBI for `ActionMailbox::InboundEmail`
   identical  sorbet/rbi/dsl/abstract_controller/caching.rbi
<internal:ast>:67:in `of': wrong argument type String (expected method) (TypeError)
	from /nix/store/37b5kvvazg85cs3bfz0yns2a4i1ldkjb-ruby-3.1.4/lib/ruby/3.1.0/error_highlight/core_ext.rb:19:in `to_s'
	from /nix/store/37b5kvvazg85cs3bfz0yns2a4i1ldkjb-ruby-3.1.4/lib/ruby/3.1.0/did_you_mean/core_ext/name_error.rb:21:in `rescue in to_s'
	from /nix/store/37b5kvvazg85cs3bfz0yns2a4i1ldkjb-ruby-3.1.4/lib/ruby/3.1.0/did_you_mean/core_ext/name_error.rb:14:in `to_s'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:114:in `message'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:114:in `handle_no_method_error?'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:36:in `rescue in run'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:20:in `run'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /nix/store/whp6r1lqw2jm7yxn2yr0m0prmln934nr-monolith-arm64-darwin-22-bundlerEnv/lib/ruby/gems/3.1.0/gems/tapioca-0.15.0/exe/tapioca:25:in `<top (required)>'
	from /Users/derekblankenship/source/noredink/monolith/bin/tapioca:29:in `load'
	from /Users/derekblankenship/source/noredink/monolith/bin/tapioca:29:in `<main>'
<internal:ast>:67:in `of': wrong argument type String (expected method) (TypeError)
	from /nix/store/37b5kvvazg85cs3bfz0yns2a4i1ldkjb-ruby-3.1.4/lib/ruby/3.1.0/error_highlight/core_ext.rb:19:in `to_s'
	from /nix/store/37b5kvvazg85cs3bfz0yns2a4i1ldkjb-ruby-3.1.4/lib/ruby/3.1.0/did_you_mean/core_ext/name_error.rb:15:in `to_s'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:114:in `message'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:114:in `handle_no_method_error?'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:36:in `rescue in run'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:20:in `run'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /nix/store/whp6r1lqw2jm7yxn2yr0m0prmln934nr-monolith-arm64-darwin-22-bundlerEnv/lib/ruby/gems/3.1.0/gems/tapioca-0.15.0/exe/tapioca:25:in `<top (required)>'
	from /Users/derekblankenship/source/noredink/monolith/bin/tapioca:29:in `load'
	from /Users/derekblankenship/source/noredink/monolith/bin/tapioca:29:in `<main>'
```

**Comment by nyghtly-derek** [comment]
Thank you @KaanOzkan! I'll try that out.

**Comment by KaanOzkan** [comment]
Yes you could clone and change that clone to revert https://github.com/Shopify/tapioca/commit/743fa37ec8ad37dd1bd2acb696aa802869cdfc3e and modify your application to point to that clone in the `Gemfile`. This is a long shot however.

Also I'm hoping that we can get a better stack trace. You could try inserting a debug statement in `Tapioca::Compilers::ActiveRecordExtensions`. Looking at the error message we should hit it. Something like `binding.b if constant == ActionMailbox::InboundEmail` at the start of your `decorate` method and then running `bin/tapioca dsl` to hit it. Then you can go through step by step and hopefully see a more informative exception.

**Comment by nyghtly-derek** [comment]
Alright, I did as instructed. Looks like the stack trace is a bit different this time. Does that help to diagnose the issue?

```
> tapioca gems

Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

Requiring all gems to prepare for compiling... /nix/store/impa1s8czp4501iv3s39cm3vibkqfdx7-ruby3.1.4-first_after_created_at-1.1.0/lib/ruby/gems/3.1.0/gems/first_after_created_at-1.1.0/lib/first_after_created_at.rb:36:in `<top (required)>': uninitialized constant ActiveRecord (NameError)
	from /nix/store/27nssdg36b4n4wsmf58spgb8gifkm2gs-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:60:in `require'
	from /nix/store/27nssdg36b4n4wsmf58spgb8gifkm2gs-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /nix/store/27nssdg36b4n4wsmf58spgb8gifkm2gs-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:55:in `each'
	from /nix/store/27nssdg36b4n4wsmf58spgb8gifkm2gs-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:55:in `block in require'
	from /nix/store/27nssdg36b4n4wsmf58spgb8gifkm2gs-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:44:in `each'
	from /nix/store/27nssdg36b4n4wsmf58spgb8gifkm2gs-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/runtime.rb:44:in `require'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/gemfile.rb:47:in `block in require_bundle'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/bundler_ext/auto_require_hook.rb:39:in `override_require_false'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/gemfile.rb:46:in `require_bundle'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/loaders/loader.rb:34:in `load_bundle'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/loaders/gem.rb:63:in `require_gem_file'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/loaders/gem.rb:35:in `load'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/loaders/gem.rb:29:in `load_application'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/commands/abstract_gem.rb:182:in `block in perform_additions'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/shell/basic.rb:44:in `indent'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/commands/abstract_gem.rb:178:in `perform_additions'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/commands/gem_sync.rb:13:in `execute'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/commands/command.rb:27:in `block in run'
	from /Users/derekblankenship/source/tapioca/lib/tapioca.rb:24:in `block in silence_warnings'
	from /nix/store/37b5kvvazg85cs3bfz0yns2a4i1ldkjb-ruby-3.1.4/lib/ruby/3.1.0/rubygems/user_interaction.rb:47:in `use_ui'
	from /Users/derekblankenship/source/tapioca/lib/tapioca.rb:23:in `silence_warnings'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/commands/command.rb:26:in `run'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `bind_call'
	from /nix/store/8r1irx615nrbi5bl24jxdzzgr3zh56js-ruby3.1.4-sorbet-runtime-0.5.11230/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11230/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
	from /Users/derekblankenship/source/tapioca/lib/tapioca/cli.rb:308:in `gem'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /nix/store/yacnyqgwfnsibmfzhnsa4b34wlfl5xll-ruby3.1.4-thor-1.2.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/derekblankenship/source/tapioca/exe/tapioca:25:in `<top (required)>'
	from /Users/derekblankenship/source/noredink/monolith/bin/tapioca:29:in `load'
	from /Users/derekblankenship/source/noredink/monolith/bin/tapioca:29:in `<main>'
```

**Comment by KaanOzkan** [comment]
Are you overriding `create_method`? I don't know who's doing `sig << RBI::SigParam.new(param.param.name, param.type)` but it's incorrect. Make sure you're using latest `tapioca` and `rbi` gems. You might have rolled back tapioca during your debugging.

Also make sure `create_method` calls in your custom compiler are correct, `parameters` kwarg should take an array of parameters i.e. `parameters: [create_param("value", type: 
T.untyped")] or parameters: [create_rest_param("args", type: "T.untyped")]`. You might be missing the `create_param` call.

**Comment by nyghtly-derek** [comment]
Alright, turns out we are overwriting `create_sig` and `create_method_with_sigs`. We did it for this reason:

```rb
# Tapioca doesn't offer a public API to declare multiple sigs in a compiler,
# but there's internal API for that. Here we define one public API to make
# that possible. We are mainly using this to define ActiveRecord::Base class
# methods like `first`, `first(n)`, `find(id)`, `find(ids)`, etc.
```

Anyways, the upgrade to 0.15.0 broke our code to overwrite those methods, because of some changes to the way that parameters work (as you pointed out above). I managed to fix the bugs such that `tapioca dsl ActionMailbox::InboundEmail` and `tapioca dsl ActionMailbox::IncinerationJob`.

However, I'm now hitting a new error on `tapioca dsl ActionMailbox::Record`. Here it is:

```
➜ tapioca --version
Tapioca v0.15.0

➜ tapioca dsl ActionMailbox::Record
Loading DSL extension classes... Done
Loading Rails application... Done
Loading DSL compiler classes... Done
Compiling DSL RBI files...

[601, 610] in /nix/store/c1z013naplgaipj7zg15fk4446z3l9mw-ruby3.1.4-parallel-1.23.0/lib/ruby/gems/3.1.0/gems/parallel-1.23.0/lib/parallel.rb
   601|           rescue Exception # # rubocop:disable Lint/RescueException
   602|             ExceptionWrapper.new($!)
   603|           end
   604|
   605|         begin
=> 606|           binding.b
   607|           Marshal.dump(result, write)
   608|         rescue Errno::EPIPE
   609|           return # parent thread already dead
   610|         end
=>#0	Parallel.process_incoming_jobs(read=#<IO:fd 14>, write=#<IO:fd 18>, job_factory=#<Parallel::JobFactory:0x0000000118041b90..., options={:in_processes=>2, :mutex=>#<Thread::Mute..., block=#<Proc:0x0000000118042720 /nix/store/z16l...) at /nix/store/c1z013naplgaipj7zg15fk4446z3l9mw-ruby3.1.4-parallel-1.23.0/lib/ruby/gems/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:606
  #1	block in worker at /nix/store/c1z013naplgaipj7zg15fk4446z3l9mw-ruby3.1.4-parallel-1.23.0/lib/ruby/gems/3.1.0/gems/parallel-1.23.0/lib/parallel.rb:577
  # and 39 frames (use `bt' command for all frames)
(rdbg) result
#<Parallel::ExceptionWrapper:0x0000000118140370
 @exception=
  #<NoMethodError: undefined method `comments' for <RBI::TypedParam param=#<RBI::BlockParam:0x00000001180b1b70 @comments=[], @loc=nil, @name="blk", @parent_tree=nil> type="T.proc.params(arg0: ::ActionMailbox::Record).returns(BasicObject)">:RBI::TypedParam

      params.all? { |p| p.comments.empty? }
                         ^^^^^^^^^>>
```

I'm not sure how to go about fixing this one. I can't find this code anywhere in our codebase:

```
params.all? { |p| p.comments.empty? }
```

I did find it in an old version of rbi that I had cached. However, I've since deleted that cache, and I seem to be on the most recent version now:

```
➜ bundle show rbi
/nix/store/b8nxnd5ranz4qrk1gd5dhpid2fihp3bz-monolith-arm64-darwin-22-bundlerEnv/lib/ruby/gems/3.1.0/gems/rbi-0.1.13
```

**Comment by nyghtly-derek** [comment]
Thanks for your help!
