### ISSUE TITLE
undefined method `filter_versions!` for an instance of `RBI::Tree`

### ISSUE THREAD

**Issue by fazo96** [Shopify/tapioca#1959]
This happens when running `bundle exec tapioca annotations`

Some information:
- Tapioca 0.15.1
- Sorbet 0.5.11481
- Bundler 2.3.17
- Ruby 3.3.2

Full error log:

```
Retrieving index from central repository... Done
Listing gems from Gemfile.lock... Done
Removing annotations for gems that have been removed...  Nothing to do
Fetching gem annotations from central repository... 
/usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/annotations.rb:231:in `filter_versions': undefined method `filter_versions!' for an instance of RBI::Tree (NoMethodError)

        rbi.filter_versions!(gem_version)
           ^^^^^^^^^^^^^^^^^
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `bind_call'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/annotations.rb:148:in `fetch_annotation'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `bind_call'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/annotations.rb:130:in `block in fetch_annotations'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/annotations.rb:130:in `select'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/annotations.rb:130:in `fetch_annotations'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `bind_call'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/annotations.rb:44:in `execute'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `bind_call'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/command.rb:27:in `block in run'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca.rb:24:in `block in silence_warnings'
        from /usr/local/rvm/rubies/ruby-3.3.2/lib/ruby/3.3.0/rubygems/user_interaction.rb:46:in `use_ui'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca.rb:23:in `silence_warnings'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `bind_call'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/commands/command.rb:26:in `run'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `bind_call'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:279:in `block in _on_method_added'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/lib/tapioca/cli.rb:360:in `annotations'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
        from /usr/local/rvm/gems/ruby-3.3.2/gems/tapioca-0.15.1/exe/tapioca:25:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-3.3.2/bin/tapioca:25:in `load'
        from /usr/local/rvm/gems/ruby-3.3.2/bin/tapioca:25:in `<main>'
        from /usr/local/rvm/gems/ruby-3.3.2/bin/ruby_executable_hooks:22:in `eval'
        from /usr/local/rvm/gems/ruby-3.3.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by egiurleo** [comment]
Opened a PR to fix - https://github.com/Shopify/tapioca/pull/1960
