### ISSUE TITLE
Incompatible with gems that call `attribute` in Rails models

### ISSUE THREAD

**Issue by ghiculescu** [Shopify/tapioca#2004]
I'm not sure if this is an issue with tapioca or with the downstream gem, but figured I'd report here and you can tell me to go away if necessary :)

To replicate:
 
- `rails new tapioca-bug`
- Add `gem "noticed", "2.4.1"` to Gemfile
- Add `gem 'tapioca', require: false` to Gemfile
- `bundle exec tapioca init`

It will raise like this:

```
/.rvm/gems/ruby-3.2.2/gems/activerecord-7.2.1/lib/active_record/connection_adapters/abstract/connection_handler.rb:224:in `retrieve_connection_pool': No connection pool for 'ActiveRecord::Base' found. (ActiveRecord::ConnectionNotEstablished)
	from /.rvm/gems/ruby-3.2.2/gems/activerecord-7.2.1/lib/active_record/connection_handling.rb:329:in `connection_pool'
	from /.rvm/gems/ruby-3.2.2/gems/activerecord-7.2.1/lib/active_record/connection_handling.rb:321:in `connection_db_config'
	from /.rvm/gems/ruby-3.2.2/gems/activerecord-7.2.1/lib/active_record/type.rb:50:in `adapter_name_from'
	from /.rvm/gems/ruby-3.2.2/gems/activerecord-7.2.1/lib/active_record/attributes.rb:299:in `resolve_type_name'
	from /.rvm/gems/ruby-3.2.2/gems/activemodel-7.2.1/lib/active_model/attribute_registration.rb:14:in `attribute'
	from /.rvm/gems/ruby-3.2.2/gems/noticed-2.4.1/app/models/noticed/event.rb:15:in `<class:Event>'
	from /.rvm/gems/ruby-3.2.2/gems/noticed-2.4.1/app/models/noticed/event.rb:2:in `<module:Noticed>'
	from /.rvm/gems/ruby-3.2.2/gems/noticed-2.4.1/app/models/noticed/event.rb:1:in `<main>'
```

The issue is the `, :json` [here](https://github.com/excid3/noticed/blob/b2f4e3cf9f377b93628497ec0c0bfd77fcef63af/app/models/noticed/event.rb#L15). If you remove that, it works fine, since it doesn't need to do the type lookup anymore.

As far as I'm aware, that approach of putting models in `app/models` for a gem is valid, but maybe there's a more correct way to structure the gem. In any case, it works fine everywhere apart from this specific case.

The underlying issue, I think, is that Rails thinks there's no connection pool set up.  This is *not* an issue when you boot a Rails app, it's only an issue when tapioca is eager loading.

cc @excid3

**Comment by KaanOzkan** [comment]
Looks like it's being thrown from https://github.com/Shopify/tapioca/blob/316688e5725e95887caa3c61f0db870229c1a0a3/lib/tapioca/runtime/reflection.rb#L51-L53

It might be fine to add `ActiveRecord::ConnectionNotEstablished` to the rescue list and skip this constant. I'm not sure if there's anything else we can do.

If `rescue` can hide legitimate cases of "missing db connection" during `tapioca dsl` then we'd need a smarter implementation.

**Comment by yiichou** [comment]
I am having the same issue with gem `public_activity`

**Comment by bradhaydon** [comment]
Thank you for the update @KaanOzkan. I appreciate you taking a look at this issue.

**Comment by marcelolx** [comment]
It seems that Tapioca doesn't work when using Rails 8 with the solid features (cache, cable, queue), all of them error out on this `connects_to` line ([cache](https://github.com/rails/solid_cache/blob/main/app/models/solid_cache/record.rb#L9), [cable](https://github.com/rails/solid_cable/blob/main/app/models/solid_cable/record.rb#L7), [queue](https://github.com/rails/solid_cache/blob/main/app/models/solid_cache/record.rb#L9))

**Comment by andrewmarkle** [comment]
We have this monkey ptach workaround in place for the time being in our application.

```ruby
module Tapioca
  module Runtime
    # This just monkey patches the constantize method to rescue ActiveRecord::AdapterNotSpecified
    # This is needed as a workaround for: https://github.com/Shopify/tapioca/issues/2004
    #
    # See also ./sorbet/rbi/shims/gems/tapioca.rbi
    module ReflectionMonkeyPatch
      # @without_runtime
      #: (String symbol, ?inherit: bool, ?namespace: Module) -> BasicObject
      def constantize(symbol, inherit: false, namespace: Object)
        namespace.const_get(symbol, inherit)
      rescue NameError, LoadError, RuntimeError, ArgumentError, TypeError, ActiveRecord::AdapterNotSpecified
        ::Tapioca::Runtime::Reflection::UNDEFINED_CONSTANT
      end
    end
  end
end

# https://github.com/Shopify/tapioca/blob/main/lib/tapioca/runtime/reflection.rb
Tapioca::Runtime::Reflection.prepend(Tapioca::Runtime::ReflectionMonkeyPatch)
```

and then in your sorbet/tapioca/require.rb file we just require this patch at the top:

```ruby
require "./lib/tapioca/runtime/reflection_monkey_patch"
```

**Comment by marcelolx** [comment]
Thanks @andrewmarkle! I will try this out later today, appreciate you sharing it 🙏
