### ISSUE TITLE
`bundle exec tapioca dsl` failing due to polymorphic association

### ISSUE THREAD

**Issue by malcolm-mergulhao** [Shopify/tapioca#233]
I'm trying to add sorbet to an existing app, and running into a weird issue when I run `bundle exec tapoica dsl`. It seems to be failing due to polymorphic associations, although I'm not totally sure if thats the root cause.

The error message is kind of confusing though, because I dont even really know what file is causing it, so I'm not sure where to start looking for problems. It generates a bunch of rbis, and the throws this exception (actual project name has been replaced by `my-project`). We are using `rails 6-1-stable`:

```
bundler: failed to load command: tapioca (/nix/store/b562r5qm44p6yzashqaxf1lbspg9zfh9-gem-bundle-my-project/lib/ruby/gems/2.7.0/bin/tapioca)
Traceback (most recent call last):
	53: from /nix/store/925idj4lmy5njx1bdar42yilgscniivv-shadowenv-ruby-env-my-project/bin/bundle:47:in `<main>'
	52: from /nix/store/925idj4lmy5njx1bdar42yilgscniivv-shadowenv-ruby-env-my-project/bin/bundle:47:in `load'
	51: from /nix/store/b562r5qm44p6yzashqaxf1lbspg9zfh9-gem-bundle-my-project/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/exe/bundle:37:in `<top (required)>'
	50: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	49: from /nix/store/b562r5qm44p6yzashqaxf1lbspg9zfh9-gem-bundle-my-project/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/exe/bundle:49:in `block in <top (required)>'
	48: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/cli.rb:24:in `start'
	47: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	46: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/cli.rb:30:in `dispatch'
	45: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	44: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	43: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	42: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/cli.rb:494:in `exec'
	41: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/cli/exec.rb:28:in `run'
	40: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
	39: from /nix/store/ardx7f1kq44r2yd53f8f38sia8j0pmr9-bundler-2.2.5/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/cli/exec.rb:63:in `load'
	38: from /nix/store/b562r5qm44p6yzashqaxf1lbspg9zfh9-gem-bundle-my-project/lib/ruby/gems/2.7.0/bin/tapioca:23:in `<top (required)>'
	37: from /nix/store/b562r5qm44p6yzashqaxf1lbspg9zfh9-gem-bundle-my-project/lib/ruby/gems/2.7.0/bin/tapioca:23:in `load'
	36: from /nix/store/b562r5qm44p6yzashqaxf1lbspg9zfh9-gem-bundle-my-project/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/exe/tapioca:6:in `<top (required)>'
	35: from /nix/store/vwi3mpm7m6r8rw5nshmql6944k5xzj7k-ruby2.7.2-thor-1.1.0/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	34: from /nix/store/vwi3mpm7m6r8rw5nshmql6944k5xzj7k-ruby2.7.2-thor-1.1.0/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	33: from /nix/store/vwi3mpm7m6r8rw5nshmql6944k5xzj7k-ruby2.7.2-thor-1.1.0/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	32: from /nix/store/vwi3mpm7m6r8rw5nshmql6944k5xzj7k-ruby2.7.2-thor-1.1.0/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	31: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/cli.rb:78:in `dsl'
	30: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca.rb:10:in `silence_warnings'
	29: from /nix/store/rmn2fcvd2kxd42jh0zha9i7ygq7niphy-ruby-2.7.2/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
	28: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca.rb:11:in `block in silence_warnings'
	27: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/cli.rb:79:in `block in dsl'
	26: from /nix/store/dpjfp2qv0bmnxd105y8b6zqi8wx3y56d-ruby2.7.2-sorbet-runtime-0.5.6292/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6292/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
	25: from /nix/store/dpjfp2qv0bmnxd105y8b6zqi8wx3y56d-ruby2.7.2-sorbet-runtime-0.5.6292/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6292/lib/types/private/methods/_methods.rb:224:in `call'
	24: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:135:in `build_dsl'
	23: from /nix/store/dpjfp2qv0bmnxd105y8b6zqi8wx3y56d-ruby2.7.2-sorbet-runtime-0.5.6292/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6292/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
	22: from /nix/store/dpjfp2qv0bmnxd105y8b6zqi8wx3y56d-ruby2.7.2-sorbet-runtime-0.5.6292/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6292/lib/types/private/methods/_methods.rb:224:in `call'
	21: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl_compiler.rb:47:in `run'
	20: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl_compiler.rb:47:in `each'
	19: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl_compiler.rb:48:in `block in run'
	18: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl_compiler.rb:87:in `rbi_for_constant'
	17: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl_compiler.rb:87:in `each'
	16: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl_compiler.rb:89:in `block in rbi_for_constant'
	15: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:113:in `decorate'
	14: from /nix/store/hym3fn64px6mrrbkqbj0pv2k88vy29f2-ruby2.7.2-parlour-5.0.0/lib/ruby/gems/2.7.0/gems/parlour-5.0.0/lib/parlour/rbi_generator/namespace.rb:134:in `path'
	13: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:116:in `block in decorate'
	12: from /nix/store/hym3fn64px6mrrbkqbj0pv2k88vy29f2-ruby2.7.2-parlour-5.0.0/lib/ruby/gems/2.7.0/gems/parlour-5.0.0/lib/parlour/rbi_generator/namespace.rb:283:in `create_module'
	11: from /nix/store/hym3fn64px6mrrbkqbj0pv2k88vy29f2-ruby2.7.2-parlour-5.0.0/lib/ruby/gems/2.7.0/gems/parlour-5.0.0/lib/parlour/rbi_generator/namespace.rb:283:in `new'
	10: from /nix/store/hym3fn64px6mrrbkqbj0pv2k88vy29f2-ruby2.7.2-parlour-5.0.0/lib/ruby/gems/2.7.0/gems/parlour-5.0.0/lib/parlour/rbi_generator/module_namespace.rb:32:in `initialize'
	 9: from /nix/store/hym3fn64px6mrrbkqbj0pv2k88vy29f2-ruby2.7.2-parlour-5.0.0/lib/ruby/gems/2.7.0/gems/parlour-5.0.0/lib/parlour/rbi_generator/namespace.rb:50:in `initialize'
	 8: from /nix/store/hym3fn64px6mrrbkqbj0pv2k88vy29f2-ruby2.7.2-parlour-5.0.0/lib/ruby/gems/2.7.0/gems/parlour-5.0.0/lib/parlour/rbi_generator/namespace.rb:50:in `yield_self'
	 7: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:118:in `block (2 levels) in decorate'
	 6: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:148:in `populate_associations'
	 5: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:148:in `each'
	 4: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:150:in `block in populate_associations'
	 3: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:227:in `populate_collection_assoc_getter_setter'
	 2: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:265:in `type_for'
	 1: from /nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:291:in `polymorphic_association?'
/nix/store/7jbqxb62ls9yl6ngqdadzwmrzm71p60y-ruby2.7.2-tapioca-0.4.14/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/compilers/dsl/active_record_associations.rb:290:in `polymorphic_association?': undefined method `through_reflection?' for nil:NilClass (NoMethodError)
```

**Comment by paracycle** [comment]
It turns out this was due to a bad association declaration in the target application. I'll close this issue and create a new issue for making errors from generators more approachable.
