### ISSUE TITLE
sync: LoadError: cannot load such file -- RMagick

### ISSUE THREAD

**Issue by jaredbeck** [Shopify/tapioca#237]
Trying to install tapioca for the first time, `sync` was unable to compile `carrierwave`. 

My app does not use RMagick. RMagick is not a runtime dependency of CarrierWave.

```
bundle exec tapioca -v
Tapioca v0.4.14
bundle exec tapioca sync
...
  Compiling carrierwave, this may take a few seconds... bundler: failed to load command: tapioca (/Users/jared/.rbenv/versions/2.6.6/bin/tapioca)
LoadError: cannot load such file -- RMagick
..../ruby/gems/2.6.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
..../ruby/gems/2.6.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
..../ruby/gems/2.6.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
..../ruby/gems/2.6.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
..../ruby/gems/2.6.0/gems/carrierwave-2.1.1/lib/carrierwave/processing/rmagick.rb:65:in `rescue in block in <module:RMagick>'
..../ruby/gems/2.6.0/gems/carrierwave-2.1.1/lib/carrierwave/processing/rmagick.rb:62:in `block in <module:RMagick>'
..../ruby/gems/2.6.0/gems/activesupport-6.1.3/lib/active_support/concern.rb:136:in `class_eval'
..../ruby/gems/2.6.0/gems/activesupport-6.1.3/lib/active_support/concern.rb:136:in `append_features'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:349:in `include'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:349:in `block (2 levels) in compile_mixes_in_class_methods'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:359:in `compile_mixes_in_class_methods'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:184:in `block in compile_body'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:634:in `with_indentation'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:176:in `compile_body'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:162:in `compile_module'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:114:in `compile_constant'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:100:in `compile'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:231:in `block in compile_subconstants'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:222:in `map'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:222:in `compile_subconstants'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:170:in `compile_module'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:114:in `compile_constant'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:100:in `compile'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:74:in `generate_from_symbol'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:32:in `block in generate'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:32:in `map'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table/symbol_generator.rb:32:in `generate'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/compilers/symbol_table_compiler.rb:19:in `compile'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:434:in `compile_gem_rbi'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:380:in `block (2 levels) in perform_additions'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:371:in `each'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:371:in `block in perform_additions'
..../ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/shell/basic.rb:44:in `indent'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:365:in `perform_additions'
..../ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6231/lib/types/private/methods/_methods.rb:233:in `call'
..../ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6231/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:150:in `sync_rbis_with_gemfile'
..../ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6231/lib/types/private/methods/_methods.rb:233:in `call'
..../ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6231/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/cli.rb:93:in `block in sync'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca.rb:11:in `block in silence_warnings'
..../ruby/2.6.0/rubygems/user_interaction.rb:47:in `use_ui'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca.rb:10:in `silence_warnings'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/lib/tapioca/cli.rb:92:in `sync'
..../ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
..../ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
..../ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
..../ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
..../ruby/gems/2.6.0/gems/tapioca-0.4.14/exe/tapioca:6:in `<top (required)>'
..../bin/tapioca:23:in `load'
..../bin/tapioca:23:in `<top (required)>'
```

**Comment by paracycle** [comment]
Ouch, thanks for this report and sorry that your first time experience failed in this way.

I know why this is failing, but not sure about the fix. There is a place in Tapioca where we try to discover the mixed-in class methods modules of a module by including all modules into a temporary class and checking the diff between the ancestors. 

The failure is happening there for the `CarrierWave::RMagick` module, since [`CarrierWave::RMagick` tries to require RMagick gem when included](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/processing/rmagick.rb#L62-L69).

I guess we could skip that operation if the module is a concern, since we know the exact class that concerns mixin anyway.

I'll try to get this fixed this week.

**Comment by jaredbeck** [comment]
Hey, no worries 😄  It's free software!

> There is a place in Tapioca where we try to discover the mixed-in class methods .. of a module by including all modules into a temporary class and checking the diff between the ancestors.

🤯 Dynamic analysis of ruby is .. wow. ❤️ This is not an easy problem

> I guess we could skip that operation if the module is a concern, since we know the exact class that concerns mixin anyway.

Like a blocklist? Or maybe rescue the LoadError and print a warning?

**Comment by paracycle** [comment]
This was released as part of [v0.4.16](https://github.com/Shopify/tapioca/releases/tag/v0.4.16), thanks for reporting the error.

**Comment by jaredbeck** [comment]
>  I did talk about some of our experiences doing that in my [RubyKaigi 2020 talk](https://www.youtube.com/watch?v=OJRQAn6BfpE) in case you are interested

Nice talk! The "Pitfalls" were scary. It's amazing some of the things people do with ruby. _sigh_ I hope that, as type-checking becomes more popular, such antics will become less popular.
