### ISSUE TITLE
Bundler 2.2.25: `materialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by vmsp** [Shopify/tapioca#413]
```
vitor@MacBook-Pro project % bundle exec tapioca sync
Removing RBI files of gems that have been removed:

bundler: failed to load command: tapioca (/Users/vitor/.rbenv/versions/2.6.6/bin/tapioca)
Traceback (most recent call last):
	49: from /Users/vitor/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
	48: from /Users/vitor/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
	47: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/exe/bundle:37:in `<top (required)>'
	46: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	45: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/exe/bundle:49:in `block in <top (required)>'
	44: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/cli.rb:25:in `start'
	43: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	42: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/cli.rb:31:in `dispatch'
	41: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	40: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	38: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/cli.rb:481:in `exec'
	37: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:28:in `run'
	36: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `kernel_load'
	35: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `load'
	34: from /Users/vitor/.rbenv/versions/2.6.6/bin/tapioca:23:in `<top (required)>'
	33: from /Users/vitor/.rbenv/versions/2.6.6/bin/tapioca:23:in `load'
	32: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/exe/tapioca:23:in `<top (required)>'
	31: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	30: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	29: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	28: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	27: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/cli/main.rb:88:in `sync'
	26: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca.rb:10:in `silence_warnings'
	25: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/user_interaction.rb:47:in `use_ui'
	24: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca.rb:11:in `block in silence_warnings'
	23: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/cli/main.rb:89:in `block in sync'
	22: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	21: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	20: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/generator.rb:180:in `sync_rbis_with_gemfile'
	19: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	18: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	17: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/generator.rb:398:in `perform_removals'
	16: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	15: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	14: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/generator.rb:363:in `removed_rbis'
	13: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	12: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	11: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/generator.rb:330:in `expected_rbis'
	10: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	 9: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	 8: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/generator.rb:203:in `bundle'
	 7: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/generator.rb:203:in `new'
	 6: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	 5: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	 4: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/gemfile.rb:34:in `initialize'
	 3: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `block in _on_method_added'
	 2: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.5.6433/lib/types/private/methods/_methods.rb:249:in `call'
	 1: from /Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/tapioca-0.4.23/lib/tapioca/gemfile.rb:62:in `load_dependencies'
/Users/vitor/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/spec_set.rb:69:in `materialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

It seems like the signature for `materialize` changed in this version.

**Comment by KaanOzkan** [comment]
PR that introduced this change: https://github.com/rubygems/rubygems/pull/4788
