### ISSUE TITLE
Spoom Encoding Issue

### ISSUE THREAD

**Issue by ryanquanz** [Shopify/tapioca#881]
when running `bin/tapioca gem activerecord` on Rails `7.0.2.3-172dfa74f861c6bfe6ee9ba438dd4094fc1a4401` I get the following error:

```
Requiring all gems to prepare for compiling...  Done

Removing RBI files of gems that have been removed:

  Nothing to do.

  Compiled activerecord
       force  sorbet/rbi/gems/activerecord@7.0.2.3-172dfa74f861c6bfe6ee9ba438dd4094fc1a4401.rbi

Typechecking RBI files...  Done
/Users/ryanquanz/.gem/ruby/3.1.1/gems/spoom-1.1.9/lib/spoom/sorbet/sigils.rb:69:in `write': "\\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/spoom-1.1.9/lib/spoom/sorbet/sigils.rb:69:in `change_sigil_in_file'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca/commands/gem.rb:425:in `block in update_strictnesses'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca/commands/gem.rb:424:in `each'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca/commands/gem.rb:424:in `update_strictnesses'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca/commands/gem.rb:81:in `execute'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca/cli.rb:235:in `block in gem'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca.rb:18:in `block in silence_warnings'
	from /opt/rubies/3.1.1/lib/ruby/3.1.0/rubygems/user_interaction.rb:46:in `use_ui'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca.rb:17:in `silence_warnings'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/sorbet-runtime-0.5.9837/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/lib/tapioca/cli.rb:198:in `gem'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/ryanquanz/.gem/ruby/3.1.1/gems/tapioca-0.7.1/exe/tapioca:23:in `<top (required)>'
	from bin/tapioca:29:in `load'
	from bin/tapioca:29:in `<main>'
```

I'm not sure if this is an issue with Spoom/Sigil or Tapioca's implementation. Workaround for now is running `bin/tapioca gem activerecord --auto_strictness false` ❤️

**Comment by elfassy** [comment]
seems to be a bug with Spoom
https://github.com/Shopify/spoom/blob/main/lib/spoom/sorbet/sigils.rb#L66-L69

**Comment by Morriar** [comment]
👋 Hey @ryanquanz,

Thanks for the bug report. As @elfassy correctly pointed out, the bug was inside `spoom`. I pushed a fix in https://github.com/Shopify/spoom/pull/125, can you give it a try please? 🙏 

You can point Spoom to my development branch with this:

```ruby
gem "spoom", github: "Shopify/spoom", branch: "at-fix-sigil-encoding"
```

Then run Tapioca again with this:

```shell
$ bundle
$ bundle exec tapioca gems activerecord
```

Thanks!

**Comment by ribeirojose** [comment]
I had the same issue and this seems to have solved it, @Morriar! Thank you 🙏
