### ISSUE TITLE
Type aliases and yard docs and tapioca v0.8

### ISSUE THREAD

**Issue by will** [Shopify/tapioca#936]
Something changed between 0.7.2 and 0.8.0, the newer version errors out unless you add `--no-doc`.

```
~/c/owl (update-gems) [1]> bin/tapioca gem --all
Requiring all gems to prepare for compiling...  Done

Removing RBI files of gems that have been removed:

  Nothing to do.

/Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/code_objects/namespace_object.rb:60:in `initialize': undefined method `new' for #<T::Private::Types::TypeAlias:0x000000010bd6dad8 @callable=#<Proc:0x000000010bd6db28 /Users/will/code/owl/config/initializers/sorbet.rb:5>> (NoMethodError)

      @attributes = SymbolHash[:class => SymbolHash.new, :instance => SymbolHash.new]
                                                   ^^^^
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/registry_store.rb:25:in `initialize'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/registry.rb:201:in `new'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/registry.rb:201:in `clear'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/registry.rb:425:in `thread_local_store'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/registry.rb:313:in `checksums'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/parser/source_parser.rb:424:in `parse'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/parser/source_parser.rb:46:in `block in parse'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/logging.rb:82:in `capture'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/parser/source_parser.rb:45:in `parse'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/parser/source_parser.rb:371:in `parse_in_order'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/parser/source_parser.rb:114:in `block in parse'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/logging.rb:182:in `enter_level'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard/parser/source_parser.rb:113:in `parse'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/yard-0.9.27/lib/yard.rb:20:in `parse'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/gemfile.rb:187:in `block in parse_yard_docs'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/gemfile.rb:187:in `each'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/gemfile.rb:187:in `parse_yard_docs'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/gem/listeners/yard_doc.rb:26:in `initialize'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/gem/pipeline.rb:43:in `new'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/gem/pipeline.rb:43:in `initialize'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/commands/gem.rb:185:in `new'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/commands/gem.rb:185:in `compile_gem_rbi'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/commands/gem.rb:76:in `block (2 levels) in execute'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/shell/basic.rb:44:in `indent'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/commands/gem.rb:75:in `block in execute'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:354:in `block in work_direct'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:353:in `work_direct'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:288:in `map'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/executor.rb:34:in `run_in_parallel'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/commands/gem.rb:74:in `execute'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/cli.rb:236:in `block in gem'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca.rb:18:in `block in silence_warnings'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/user_interaction.rb:46:in `use_ui'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca.rb:17:in `silence_warnings'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `bind_call'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10010/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/lib/tapioca/cli.rb:199:in `gem'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/will/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/tapioca-0.8.0/exe/tapioca:23:in `<top (required)>'
	from bin/tapioca:29:in `load'
	from bin/tapioca:29:in `<main>'
```

The line it's upset about in config/initializers/sorbet.rb:5 is 

`SymbolHash = T.type_alias { T::Hash[Symbol, T.untyped] }`

Strangely the line before, which doesn't make it into the errors, is very similar

`JsonHash = T.type_alias { T::Hash[String, T.untyped] }`

adding `--no-doc` to the command lets everything get generated normally as it did on older versions of tapioca

**Comment by will** [comment]
Thanks for finding the actual cause. How did you figure out that yard has the same constant?
