### ISSUE TITLE
SystemStackError on generating gem rbis on v0.8.0

### ISSUE THREAD

**Issue by okhwaja** [Shopify/tapioca#942]
👋  i just upgraded tapioca and I'm seeing issues with the new tapioca version when trying to regenerate rbis for a gem after upgrading

before (tapioca 0.5.2)

```
./bin/tapioca gem dynamoid
Requiring all gems to prepare for compiling... You can remove `require 'dalli/cas/client'` as this code has been rolled into the standard 'dalli/client'.
 Done

Processing 'dynamoid' gem:
  Compiling dynamoid, this may take a few seconds...   Done

All operations performed in working directory.
Please review changes and commit them.
```

after (v0.8.0)
```
./bin/tapioca gem dynamoid
Requiring all gems to prepare for compiling... Traceback (most recent call last):
	10481: from ./bin/tapioca:29:in `<main>'
	10480: from ./bin/tapioca:29:in `load'
	10479: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/tapioca-0.8.0/exe/tapioca:23:in `<top (required)>'
	10478: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	10477: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	10476: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	10475: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	10474: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/tapioca-0.8.0/lib/tapioca/cli.rb:199:in `gem'
	 ... 10469 levels...
	    4: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/tapioca-0.8.0/lib/tapioca/runtime/trackers/mixin.rb:32:in `register'
	    3: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10028/lib/types/_types.rb:256:in `[]'
	    2: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10028/lib/types/_types.rb:256:in `new'
	    1: from /Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.10028/lib/types/types/typed_enumerable.rb:12:in `initialize'
/Users/osmankhwaja/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/tapioca-0.8.0/lib/tapioca/sorbet_ext/generic_name_patch.rb:103:in `coerce': stack level too deep (SystemStackError)
```

my `sorbet/tapioca/require.rb` file is empty

any advice? 🙇‍♂️

**Comment by Morriar** [comment]
👋 Hey Osman,

Thanks for the bug report.

Unfortunately I haven't been able to reproduce this problem with `dynamoid` + Tapioca 0.8.0 on Ruby 2.7.4.

It would be super useful if you could provide us with a minimal reproduction, for example a small repository using only the gems required to reproduce the issue.

Thanks!

**Comment by Morriar** [comment]
I'm closing for now, feel free to reopen 👍

**Comment by mlarraz** [comment]
Hi, this is still an issue. It has nothing to do with the dynamoid gem. This happens when trying to generate RBIs for any gem. While I can't reproduce this in a new repo, I don't believe we're doing anything custom enough with Sorbet to trigger this behavior
